# deployment.yaml for shapley.io-api
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shapley.io-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shapley.io-api
  template:
    metadata:
      labels:
        app: shapley.io-api
    spec:
      containers:
      - name: shapley.io-api
        image: shapley.io-api:latest
        ports:
        - containerPort: 8080