# deployment.yaml for orion-api
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orion-api
  template:
    metadata:
      labels:
        app: orion-api
    spec:
      containers:
      - name: orion-api
        image: orion-api:latest
        ports:
        - containerPort: 8080