version: '2.4'
services:
  shapley.io-api:
    container_name: shapley.io-api
    extends:
      file: docker-compose.common.yml
      service: api
    ports:
      - "8080:8080"
    environment:
      - SHAPLEY_IO_REDIS_HOST=redis
      - SHAPLEY_IO_REDIS_PORT=6379
    networks:
      - backend
  
  redis:
    container_name: redis
    extends:
      file: docker-compose.common.yml
      service: redis
    ports:
      - "6379:6379"

  postgres:
    container_name: postgres
    extends:
      file: docker-compose.common.yml
      service: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shapley_io
      - POSTGRES_USER=shapley_io
      - POSTGRES_PASSWORD=shapley_io
    networks:
      - backend

networks:
  backend: